### ISSUE TITLE
Missing Serve fastapi decorater

### ISSUE THREAD

**Issue by dineshbvadhia** [AlexandreBrown/RayServePrototype#1]
Should it be:
```
@serve.deployment(route_prefix="/landing-spot")
@serve.ingress(app)
class LandingSpotInference:
    def __init__(self): ...

```per https://docs.ray.io/en/latest/serve/http-servehandle.html?highlight=starlette#basic-example ?

**Comment by AlexandreBrown** [comment]
Hello @dineshbvadhia , I believe you are correct.  
At the time the prototype was written the documentation was not updated to use  `@serve.ingress(app)`.  
But I believe that now, using `@serve.ingress(app)` is the recommended approach they have in their doc.
